# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c261c34fe7199d6e57709c7fb5cb00c2b4731500a11c66b623ba41ca26e3c570a740208c412c22a1e8eaad7b46e0235d18ff5c1b64af65126dd00c6e0a35f58e

test:
  secret_key_base: 94ff3dc12fc1c30b7f438f90f42ef5f817294616ac2350bf14b13d9abbad07d94b7d02cc2bafbe6891485e6a2ccfa254c4a19cd012d936b9bc794c02f7e44edc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
